// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmvnofmtmvnwuqgijrpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdtdm5vZm10bXZud3VxZ2lqcnBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjY0NzMsImV4cCI6MjA2MjgwMjQ3M30.yzchyyl9tUGcXvivV5EE0DJg2ieb6hmwn9rMUOUDxLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);